# Generated by Django 4.2.2 on 2023-08-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail_images',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
